### ISSUE TITLE
Package breaks tests when used with ES6 imports

### ISSUE THREAD

**Issue by rickstaa** [buttons/react-github-btn#27]
When I try to use this package inside an ES6 typescript project, I receive the `SyntaxError: Cannot use import statement outside a module` (see error below). I now solved this by mocking the `react-github-btn` package but wanted to let you know that something goes wrong.

```bash
Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/ricks/Development/personal/cra-test-test/react-github-btn-cra-ts-test/node_modules/react-github-btn/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import React, { PureComponent } from 'react'
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import GitHubButton from "react-github-btn";
        | ^
      2 | import "./App.css";
      3 | import logo from "./logo.svg";
      4 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/App.tsx:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.692 s
Ran all test suites related to changed files.
```

### How to reproduce

1. Clone the [example repository](https://github.com/rickstaa/react-github-btn-cra-ts-test).
2. Install the dependencies using `npm i`.
3. Run `npm run test`.
4. See error occuring.

**Comment by ntkme** [comment]
From the hints:

> By default "node_modules" folder is ignored by transformers.

> To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.

**Comment by rickstaa** [comment]
@ntkme Your right! Thanks, I found [the following solution](https://github.com/facebook/create-react-app/issues/2537#issuecomment-406166713), which solves my problem.
